export const WEEKLY_DUMMY = {
  titleListMap: {
    월: [
      {
        titleId: 805437,
        titleName: '피폐물의 해피엔딩을 위하여',
        author: '호',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/805437/thumbnail/thumbnail_IMAG21_b42c6ad3-4ca8-4cdb-8dfb-7671b2fea0c0.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.95279,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 817019,
        titleName: '날 먹는 건 금지양!',
        author: '조9',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/817019/thumbnail/thumbnail_IMAG21_22cf1c1b-376e-40ee-b643-a48db411247a.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.96598,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 808760,
        titleName: '어쌔신 크리드 - 잊혀진 사원',
        author: 'NOHT, ARC, Ubisoft / Tabii',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/808760/thumbnail/thumbnail_IMAG21_1d65caac-a10d-44c5-b49d-ef1ac0b95a17.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.88977,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 803123,
        titleName: '연애 연기대상',
        author: '김충전 / 일공팔',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/803123/thumbnail/thumbnail_IMAG21_8044b60b-1ab2-4849-9640-b3d2f6500068.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.9106,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 812403,
        titleName: '컨트롤X',
        author: '사이렌 / 서클',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/812403/thumbnail/thumbnail_IMAG21_33b2a737-0fe1-41d8-b083-40220fb5c5cb.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.51371,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
    ],
    화: [
      {
        titleId: 810561,
        titleName: '왕자님 짠내밥상',
        author: '쑥',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/810561/thumbnail/thumbnail_IMAG21_b93e29dc-335c-4c38-afa9-074c581273cc.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.53407,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 798101,
        titleName: '왕게임',
        author: '신형욱 / 범고래',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/798101/thumbnail/thumbnail_IMAG21_766e3761-228a-4c04-97b8-6f0ef13cf35b.jpg',
        up: false,
        rest: true,
        bm: false,
        adult: false,
        starScore: 9.85426,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 809263,
        titleName: '대리게임',
        author: '철준',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/809263/thumbnail/thumbnail_IMAG21_10493e4c-e4b5-4aac-b1ed-4acd07879e54.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.23772,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 804653,
        titleName: '유사연애',
        author: '여은',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/804653/thumbnail/thumbnail_IMAG21_245d93e8-07c6-4229-9e51-bb813a307610.jpg',
        up: false,
        rest: true,
        bm: false,
        adult: false,
        starScore: 9.87195,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
    ],
    수: [
      {
        titleId: 758662,
        titleName: '급식아빠',
        author: '김재한',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/758662/thumbnail/thumbnail_IMAG21_0c8a2c9e-b2de-4346-8ac6-c8e2c0a5bfe5.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.74808,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 765158,
        titleName: '괴물공작의 딸',
        author: '한바다 / 찬란',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/765158/thumbnail/thumbnail_IMAG21_1a3c20c6-14fc-44c7-8f88-7512dbcb2321.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.75122,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 826417,
        titleName: '정상가족',
        author: '박새이',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/826417/thumbnail/thumbnail_IMAG21_7a3ef101-8f96-4a8e-b901-577926d80916.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.83,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 808201,
        titleName: '이혼은 쉬운데, 연애는 어렵다',
        author: '수빙 / 팔가락 / 쥬시린시',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/808201/thumbnail/thumbnail_IMAG21_6d03dfbf-176d-49ef-a06f-63a12674b4a0.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.93269,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
    ],
    목: [
      {
        titleId: 812354,
        titleName: '육아일기',
        author: '자까',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/812354/thumbnail/thumbnail_IMAG21_be53c95b-d800-4275-8869-e9b9a8413ce8.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.95447,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 747271,
        titleName: '나노마신',
        author: '현절무 / 금강불괴 / 한중월야',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/747271/thumbnail/thumbnail_IMAG21_75c6a3cc-c4d1-4b51-a945-029aff772a63.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.86173,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 822640,
        titleName: '소꿉친구 컴플렉스',
        author: '은하이',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/822640/thumbnail/thumbnail_IMAG21_56a8443c-14b8-47a6-8806-ae90f935cd85.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: true,
        starScore: 9.96186,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
    ],
    금: [
      {
        titleId: 827578,
        titleName: '북설애담',
        author: '휘요',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/827578/thumbnail/thumbnail_IMAG21_d4a68180-68f0-4e71-918e-6f3752200ddc.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.94126,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 817048,
        titleName: '야수라는 공작에게 시집왔는데',
        author: '나양 / 김승혁 / 박약초',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/817048/thumbnail/thumbnail_IMAG21_c361fb33-b1c2-478a-8b56-4f8eb3725726.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.93944,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 792139,
        titleName: '솔트앤페퍼',
        author: '소이',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/792139/thumbnail/thumbnail_IMAG21_7075778868856305717.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.97364,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 822577,
        titleName: '소희 훔치기',
        author: '세라비 / 2L',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/822577/thumbnail/thumbnail_IMAG21_37e8d3f6-2cf5-4872-bdbc-2436dd140eab.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.29102,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 780063,
        titleName: '달이 없는 나라',
        author: '엥비',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/780063/thumbnail/thumbnail_IMAG21_3978478587194062641.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.97223,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 793853,
        titleName: '악마라고 불러다오',
        author: '자양 / 써나 / 안테',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/793853/thumbnail/thumbnail_IMAG21_f4d3c4d2-b594-4123-925e-e141fdebd4da.jpg',
        up: false,
        rest: true,
        bm: false,
        adult: false,
        starScore: 9.96561,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
    ],
    토: [
      {
        titleId: 818791,
        titleName: '개꿈',
        author: '신송림',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/818791/thumbnail/thumbnail_IMAG21_a613db8b-8319-4bfe-8971-1df89f4df979.jpg',
        up: true,
        rest: false,
        bm: false,
        adult: true,
        starScore: 9.92838,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 833255,
        titleName: '낢이 사는 이야기 - 계속되는 미미한 인생',
        author: '서나래',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/833255/thumbnail/thumbnail_IMAG21_504f6152-8a60-42a0-a1c0-43cd77f9c430.jpg',
        up: true,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.94723,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: true,
      },
      {
        titleId: 826670,
        titleName: '아수라',
        author: '류기운 / 문정후',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/826670/thumbnail/thumbnail_IMAG21_ecfd3f55-b872-45a8-9837-a94d1dcb9f72.jpg',
        up: true,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.94501,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
    ],
    일: [
      {
        titleId: 812354,
        titleName: '육아일기',
        author: '자까',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/812354/thumbnail/thumbnail_IMAG21_be53c95b-d800-4275-8869-e9b9a8413ce8.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.95447,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 811721,
        titleName: '무직백수 계백순',
        author: '지발',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/811721/thumbnail/thumbnail_IMAG21_4db2b4b4-ba56-4768-b13f-a81d69e508f5.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.89771,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 758150,
        titleName: '입학용병',
        author: 'YC / 락현',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/758150/thumbnail/thumbnail_IMAG21_4135492154714961716.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.89984,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 821851,
        titleName: '기기괴괴2',
        author: '오성대',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/821851/thumbnail/thumbnail_IMAG21_d67261bc-0aea-495c-b92e-07dc2c1785cd.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.86157,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
      {
        titleId: 737628,
        titleName: '별이삼샵',
        author: '혀노',
        thumbnailUrl:
          'https://image-comic.pstatic.net/webtoon/737628/thumbnail/thumbnail_IMAG21_9e108875-36b5-4872-8ace-53a6e492376b.jpg',
        up: false,
        rest: false,
        bm: false,
        adult: false,
        starScore: 9.96373,
        viewCount: 0,
        openToday: false,
        potenUp: false,
        bestChallengeLevelUp: false,
        finish: false,
        new: false,
      },
    ],
  },
  dayOfWeek: '토',
};
