import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import ReactQueryProvider from '@/hook/provider/usereactquery';
import Header from '@/component/common/header/header';
import Footer from '@/component/common/footer/footer';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='text-[12px] sm:text-[14px] lg:text-[16px] qhd:text-[24px] 4k:text-[32px]'
    >
      <body
        className={`${pretendard.className} scrollbar flex flex-col items-center `}
      >
        <Header />
        <div id='modal-root' />
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
