import type { Metadata } from 'next';
import './globals.css';
import ReactQueryProvider from '@/hook/provider/usereactquery';
import JotaiProvider from '@/hook/provider/jotai-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const initialState = {
    // isMobile: false, // 기본값 설정
    isLogin: false, // 기본값 설정
  };
  return (
    <html lang='en'>
      <head>
        <link
          rel='preload'
          as='style'
          href='https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css'
          crossOrigin='anonymous'
        />
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css'
        />
      </head>

      <body className='font-pretendard scrollbar'>
        <div id='modal-root' />
        <JotaiProvider initialState={initialState}>
          <ReactQueryProvider>
            {children}
            {modal}
          </ReactQueryProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
