#!/bin/sh

FORBIDDEN_HTTPS_URL="<https://github.com/Project-aniwhere/Aniwhere-FE.git>" # 레포 https url 
FORBIDDEN_SSH_URL="git@github.com:Project-aniwhere/Aniwhere-FE.git" # 레포 ssh url
FORBIDDEN_REF_MAIN="refs/heads/main"

remote="$1"
url="$2"

if [ "$url" != "$FORBIDDEN_HTTPS_URL" -a "$url" != "$FORBIDDEN_SSH_URL" ]
then
    echo "forked branch can push your commits"
    exit 0 # Forked Project 에서는 제한하지 않음
fi

if read local_ref local_sha remote_ref remote_sha
then
  echo "현재 푸쉬하는 브랜치는 $local_ref 내부입니다."
    if [ "$remote_ref" == "$FORBIDDEN_REF_MAIN" ]
    then
        echo "DO NOT PUSH TO MAIN"
        exit 1 # 금지된 ref 로 push 를 실행하면 에러
    fi
fi

exit 0